### ISSUE TITLE
JOSS: Performance of code

### ISSUE THREAD

**Issue by Alex-Vasile** [uw-comphys/opencmp#6]
1. Is it possible to run your code in parallel?
2. In the paper you mention, that utilizing MPI is planned but are you able to use shared memory?
3. Have you compared the performance of your code against other codes? 
4. Do you have performed three-dimensional simulations?"

per: https://github.com/openjournals/joss-reviews/issues/3742#issuecomment-940420033

**Comment by nasserma** [comment]
@bonh It is currently possible to run OpenCMP using shared-memory parallelization (numthreads parameter in config file). The underlying finite element library, NGSolve, also supports distributed memory parallelization using MPI, but OpenCMP currently does not support this usage. We are planning this in the future (2022).

We have not tested the performance of OpenCMP against other packages, however, the underlying finite element library has a performance analysis found [here]([url](https://www.asc.tuwien.ac.at/~schoeberl/wiki/publications/ngs-cpp11.pdf)).

We have performed 3D simulations using shared memory parallelization, we are creating a tutorial demonstrating this shortly.

**Comment by bonh** [comment]
In my opinion some sort of shared memory parallelization is mandatory for modern CFD tools (can you think of any tool without MPI or something similar so that it can run on a supercomputer?). Otherwise the tool might just be a great educational package (which is not bad per se, but I do not think this is your goal, right?). So perhaps it might be a good idea to include the MPI capabilities of NGSolve into OpenCMP before publishing a paper in JOSS, don't you think? However, I am really looking forward to the 3D simulation example using shared memory parallelization!

**Comment by bonh** [comment]
Oh, sry, I meant "distributed memory": 
> In my opinion some sort of **distributed memory** parallelization is mandatory for modern CFD tools

**Comment by nasserma** [comment]
> Oh, sry, I meant "distributed memory":
> 
> > In my opinion some sort of **distributed memory** parallelization is mandatory for modern CFD tools

OK, then from my understanding you are requiring use to implement distributed-memory parallelization for this submission?

**Comment by bonh** [comment]
By no means "requiring"! But you wrote yourself that you plan to implement it in 2022. And I just think that is a great idea! So I am merely suggesting that the implementation of a distributed parallelization would greatly enhance the publication. Otherwise I would need to look for the 3D simulations. But just to be clear, in my opinion, a CFD package which is not able to at least simulate moderate scale problems (which you have to demonstrate as of yer, distributed or shared memory) AND does not implement some new methodology (see the discussion of the diffuse interface method) does not meet the "scholarly effort" described by JOSS.

**Comment by nasserma** [comment]
We have added a tutorial to show how OpenCMP can be used to solve a 3D problem (heat conduction) with the diffuse interface method, instead of a conformal mesh, for a relatively complex geometry. The tutorial is provided here,

https://opencmp.io/tutorials/tutorial_10.html

We have not added the example to the paper, but if this is desirable please let us know and we will add a section "showing off" the diffuse interface method.

**Comment by nasserma** [comment]
Based on your comments here,

https://github.com/openjournals/joss-reviews/issues/3742#issuecomment-1008759727

I am closing this issue, however, we have added MPI functionality to our ongoing projects list.

**Comment by bonh** [comment]
I am trying to get tutorial 10 to run. I am on branch `publications`. Following the documentation I try `python3 -m opencmp config_IC` but it fails with 
```
importing NGSolve-6.2.2105
Using the default value of False for TRANSIENT, transient.
WARNING: Physical groups detected - Be sure to define them for every geometrical entity.
 Curve elements, order = 2
WARNING: The direct linear solver does not respect the num_threads parameter you may have set.This is an NGSolve issue
Traceback (most recent call last):
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/root/opencmp/opencmp/__main__.py", line 29, in <module>
    run(config_file_path)
  File "/root/opencmp/opencmp/run.py", line 66, in run
    calc_error(config_parser, solver.model, sol)
  File "/root/opencmp/opencmp/helpers/error.py", line 305, in calc_error
    surface_traction = _surface_traction(sol, model, marker)
  File "/root/opencmp/opencmp/helpers/error.py", line 222, in _surface_traction
    raise ValueError('{} is not a mesh surface.'.format(marker))
ValueError: c is not a mesh surface.
```

**Comment by bonh** [comment]
Okay, the example runs through, all good. But the visualization of `output/transient.pvd` with paraview v.5.10.0 fails with the errors below. What kind of version of paraview are you using? Or do you recommend a different software?
```
ERROR: In /builds/gitlab-kitware-sciviz-ci/build/superbuild/paraview/src/VTK/IO/XMLParser/vtkXMLParser.cxx, line 379
vtkXMLDataParser (0x18d30190): Error parsing XML in stream at line 8, column 10, byte index 241: junk after document element

ERROR: In /builds/gitlab-kitware-sciviz-ci/build/superbuild/paraview/src/VTK/IO/XML/vtkXMLReader.cxx, line 521
vtkPVDReader (0x17763f80): Error parsing input file.  ReadXMLInformation aborting.

ERROR: In /builds/gitlab-kitware-sciviz-ci/build/superbuild/paraview/src/VTKExtensions/IOCore/vtkPVDReader.cxx, line 133
vtkPVDReader (0x17763f80): Could not read file information

ERROR: In /builds/gitlab-kitware-sciviz-ci/build/superbuild/paraview/src/VTK/Common/ExecutionModel/vtkExecutive.cxx, line 753
vtkPVCompositeDataPipeline (0x18d5d930): Algorithm vtkPVDReader(0x17763f80) returned failure for request: vtkInformation (0x170c33b0)
  Debug: Off
  Modified Time: 386992
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0



ERROR: In /builds/gitlab-kitware-sciviz-ci/build/superbuild/paraview/src/VTKExtensions/IOCore/vtkPVDReader.cxx, line 133
vtkPVDReader (0x17763f80): Could not read file information

ERROR: In /builds/gitlab-kitware-sciviz-ci/build/superbuild/paraview/src/VTK/Common/ExecutionModel/vtkExecutive.cxx, line 753
vtkPVCompositeDataPipeline (0x18d5d930): Algorithm vtkPVDReader(0x17763f80) returned failure for request: vtkInformation (0x170c33b0)
  Debug: Off
  Modified Time: 386992
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0



ERROR: In /builds/gitlab-kitware-sciviz-ci/build/superbuild/paraview/src/VTKExtensions/IOCore/vtkPVDReader.cxx, line 133
vtkPVDReader (0x17763f80): Could not read file information

ERROR: In /builds/gitlab-kitware-sciviz-ci/build/superbuild/paraview/src/VTK/Common/ExecutionModel/vtkExecutive.cxx, line 753
vtkPVCompositeDataPipeline (0x18d5d930): Algorithm vtkPVDReader(0x17763f80) returned failure for request: vtkInformation (0x170c33b0)
  Debug: Off
  Modified Time: 386992
  Reference Count: 1
  Registered Events: (none)
  Request: REQUEST_DATA_OBJECT
  ALGORITHM_AFTER_FORWARD: 1
  FORWARD_DIRECTION: 0
```

**Comment by bonh** [comment]
```
pip show configparser
Name: configparser
Version: 5.2.0
Summary: Updated configparser from Python 3.8 for Python 2.6+.
Home-page: https://github.com/jaraco/configparser/
Author: Łukasz Langa
Author-email: lukasz@langa.pl
License: UNKNOWN
Location: /usr/local/lib/python3.8/dist-packages
Requires: 
Required-by: 
```

**Comment by bonh** [comment]
Just tried to open the results from `python3 -m opencmp config_IC` with `paraview 5.7.0` and it worked perfectly.

**Comment by nasserma** [comment]
> Running the example works now. Here is the version info:
> 
> ```
> pip show configparser
> Name: configparser
> Version: 5.2.0
> Summary: Updated configparser from Python 3.8 for Python 2.6+.
> Home-page: https://github.com/jaraco/configparser/
> Author: Łukasz Langa
> Author-email: lukasz@langa.pl
> License: UNKNOWN
> Location: /usr/local/lib/python3.8/dist-packages
> Requires: 
> Required-by: 
> ```

This seems to be a bug in the configparser module, using version 5.2.0 is treating the string "cyl" as a list for some reason, version 5.1.0 and previous versions do not do this (as expected). I will look into whether or not something changed in v5.2.0 that we need to account for, but it will take me a bit of time.

I think the same is the case with the Paraview issue, the .pvd file we create seems to have issues with v5.9 and higher.

**Comment by bonh** [comment]
I confirm that it works with `paraview 5.7` if I open the `*.vtu` file directly but not with `transient.pvd`.

**Comment by bonh** [comment]
I am done here and fine with closing the issue.

**Comment by bonh** [comment]
Good work!
